import { CheckCircle2, FlaskConical, LockKeyhole, RotateCcw, Sparkles, ThumbsUp } from "lucide-react";
import { approveScript, decideExperiment } from "@/app/actions";
import { Badge, EmptyState, PageTitle } from "@/components/ui";
import { formatDateTime } from "@/lib/format";
import { getExperiments, getScripts } from "@/lib/repository";

export default async function ScriptsPage() {
  const [scripts, experiments] = await Promise.all([getScripts(), getExperiments()]);
  return <><PageTitle eyebrow="Controlled learning" title="Script intelligence" description="Every change is versioned, evidence-backed, and kept separate from fixed campaign guardrails." />
    <section className="experiment-list">{experiments.map((experiment) => {
      const calls = Number(experiment.human_calls || 0);
      const target = Number(experiment.target_human_calls || 5);
      const progress = Math.min(100, target ? (calls / target) * 100 : 0);
      const ready = calls >= target;
      const result = experiment.result && typeof experiment.result === "object" ? experiment.result as Record<string, unknown> : {};
      return <article className="panel experiment-card" key={String(experiment.id)}><div className="experiment-top"><div className="experiment-icon"><FlaskConical size={18} /></div><div><span className="eyebrow">Five-call canary · {String(experiment.status)}</span><h2>{String(experiment.baseline_version)} vs {String(experiment.variant_version)}</h2><p>Metric: {String(experiment.success_metric).replaceAll("_", " ")}</p></div><Badge status={ready ? "ready" : String(experiment.status)}>{calls} / {target} human calls</Badge></div><div className="experiment-progress"><span style={{ width: `${progress}%` }} /></div><div className="experiment-details"><div><span>Rollback condition</span><p>{String(experiment.rollback_condition)}</p></div><div><span>Observed result</span><p>{String(result.summary || "Collecting transcript-supported outcomes.")}</p></div></div>{String(experiment.status) === "running" ? <form action={decideExperiment} className="experiment-decision"><input type="hidden" name="id" value={String(experiment.id)} /><label>Decision notes<textarea name="notes" rows={2} placeholder="Reference the five calls and explain the evidence." required /></label><button className="primary-button" name="decision" value="keep" disabled={!ready}><ThumbsUp size={14} /> Keep variant</button><button className="secondary-button" name="decision" value="revert" disabled={!ready}><RotateCcw size={14} /> Revert</button>{!ready ? <small>A keep/revert decision unlocks after five human-connected canary calls.</small> : null}</form> : <div className="change-note"><CheckCircle2 size={15} /><div><strong>Decision recorded</strong><span>{String(experiment.status).replaceAll("_", " ")} · {formatDateTime(experiment.decided_at as string | null)}</span></div></div>}</article>;
    })}</section>
    <section className="script-layout"><div className="script-list">{scripts.length ? scripts.map((script) => <article className="panel script-card" key={String(script.id)}><div className="panel-heading"><div><span className="eyebrow">{String(script.version)}</span><h2>{script.status === "active" ? "Current calling script" : script.status === "canary" ? "Canary script" : "Proposed adjustment"}</h2></div><Badge status={String(script.status)}>{String(script.status)}</Badge></div><p className="script-content">{String(script.content)}</p>{script.change_summary ? <div className="change-note"><Sparkles size={16} /><div><strong>Why this changed</strong><span>{String(script.change_summary)}</span></div></div> : null}{Array.isArray(script.evidence) && script.evidence.length ? <div className="script-evidence"><strong>Evidence and test plan</strong><ul>{script.evidence.map((item: string) => <li key={item}>{item}</li>)}</ul></div> : null}<small>Created {formatDateTime(script.created_at as string)}</small>{script.status === "proposed" ? <form action={approveScript}><input type="hidden" name="id" value={String(script.id)} /><button className="primary-button"><FlaskConical size={16} /> Start five-call canary</button></form> : null}</article>) : <EmptyState title="No script versions" body="Seed the campaign baseline to begin controlled learning." />}</div>
      <aside className="panel guardrails-panel"><div className="panel-heading"><div><span className="eyebrow">Immutable controls</span><h2>Fixed guardrails</h2></div><LockKeyhole size={19} /></div>{scripts[0]?.fixed_guardrails && Array.isArray(scripts[0].fixed_guardrails) ? <ul>{scripts[0].fixed_guardrails.map((item: string) => <li key={item}><CheckCircle2 size={15} />{item}</li>)}</ul> : <p>Guardrails load with the active script.</p>}</aside>
    </section>
  </>;
}
