import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ExternalLink, MapPin, Microscope, Phone, RefreshCw, ShieldAlert, Star } from "lucide-react";
import { Badge, EmptyState, PageTitle } from "@/components/ui";
import { ConversationScorecard } from "@/components/conversation-scorecard";
import { queueDeepResearch, refreshLeadResearchProfile, updateLeadStage } from "@/app/actions";
import { formatDateTime, phoneDisplay } from "@/lib/format";
import { getLead } from "@/lib/repository";
import { deriveResearchProfile } from "@/lib/sales-intelligence";
import { loadBusinessProfile } from "@/lib/business-config";

export default async function LeadPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { lead, calls, followUps, meetingBriefs } = await getLead(id);
  if (!lead) notFound();
  const research = deriveResearchProfile(lead);
  const profile = loadBusinessProfile();
  return <>
    <Link className="back-link" href="/leads"><ArrowLeft size={15} /> Back to pipeline</Link>
    <PageTitle eyebrow={`${lead.id} · ${lead.category}`} title={lead.business} description={`${lead.city} · ${lead.presence_class}`} action={<Badge status={lead.pipeline_stage}>{lead.pipeline_stage}</Badge>} />
    <section className="lead-grid">
      <article className="panel span-2"><div className="panel-heading"><div><span className="eyebrow">Account brief</span><h2>Business and opportunity</h2></div></div><div className="detail-grid"><div><span>Phone</span><strong><Phone size={15} /> {phoneDisplay(lead.phone)}</strong></div><div><span>Location</span><strong><MapPin size={15} /> {lead.address ?? lead.city}</strong></div><div><span>Rating</span><strong><Star size={15} /> {lead.rating ? `${lead.rating} · ${lead.review_count ?? 0} reviews` : "Not recorded"}</strong></div><div><span>Lead score</span><strong>{lead.lead_score} · {lead.priority} priority</strong></div><div><span>Attempts</span><strong>{lead.attempt_count} of {profile.operations.maxLifetimeAttempts}</strong></div><div><span>Next follow-up</span><strong>{formatDateTime(lead.next_follow_up_at)}</strong></div></div><div className="evidence-box"><span>Presence evidence</span><p>{lead.evidence_notes || "No evidence notes recorded."}</p><div className="source-links">{lead.primary_source_url ? <a href={lead.primary_source_url} target="_blank" rel="noreferrer">Primary source <ExternalLink size={13} /></a> : null}{lead.presence_check_url ? <a href={lead.presence_check_url} target="_blank" rel="noreferrer">Presence check <ExternalLink size={13} /></a> : null}</div></div></article>
      <article className="panel"><div className="panel-heading"><div><span className="eyebrow">Pipeline control</span><h2>Update stage</h2></div></div><form action={updateLeadStage} className="stack-form"><input type="hidden" name="id" value={lead.id} /><select name="stage" defaultValue={lead.pipeline_stage}>{["New","Research","Qualified","Scheduled","Attempted","Contacted","Voicemail","Callback","Interested","Meeting","Not interested","Disqualified"].map((stage) => <option key={stage}>{stage}</option>)}</select><button className="primary-button">Save stage</button></form>{lead.do_not_call ? <div className="danger-note"><strong>Do not call</strong><span>{lead.dnc_reason}</span></div> : null}</article>
      <article className="panel span-2"><div className="panel-heading"><div><span className="eyebrow">Evidence-grounded preparation</span><h2>Pre-call intelligence</h2></div><Badge status={research.status}>{research.status.replaceAll("_", " ")}</Badge></div>
        <div className="research-grid"><div className="research-column"><span className="section-label">Verified facts</span>{research.verifiedFacts.length ? <ul className="fact-list">{research.verifiedFacts.map((fact, index) => <li key={`${fact.fact}-${index}`}><p>{fact.fact}</p><small>{fact.verifiedOn ? `Verified ${fact.verifiedOn}` : "Date unavailable"}{fact.sourceUrl ? <> · <a href={fact.sourceUrl} target="_blank" rel="noreferrer">source <ExternalLink size={11} /></a></> : null}</small></li>)}</ul> : <div className="warning-note">No sufficiently sourced facts are stored. Review the lead before using a personalized observation.</div>}</div>
          <div className="research-column"><span className="section-label">Hypotheses to validate</span><ul className="hypothesis-list">{research.hypotheses.map((item) => <li key={item}>{item}</li>)}</ul><p className="research-warning">These are not prospect facts and must never be stated as confirmed problems.</p></div></div>
        <div className="brief-grid"><div><span>ICP preparation profile</span><strong>{research.icpProfile.name}</strong><small>{research.icpProfile.fit === "matched" ? "Category match" : "Generic fallback — review before use"}</small></div><div><span>Local buying authority</span><strong>{research.localAuthority.status.replaceAll("_", " ")}</strong><small>{research.localAuthority.buyingAuthorityReason}</small></div><div><span>Decision-maker</span><strong>{research.decisionMakerRole}</strong></div><div><span>Personalized observation</span><strong>{research.personalizedObservation || "Do not personalize until facts are verified."}</strong><small>{research.personalizedObservationEvidence ? <>Supported by a source verified {research.personalizedObservationEvidence.verifiedOn || "on an unknown date"}.{research.personalizedObservationEvidence.sourceUrl ? <> <a href={research.personalizedObservationEvidence.sourceUrl} target="_blank" rel="noreferrer">View evidence <ExternalLink size={10} /></a></> : null}</> : "No supporting source — do not use."}</small></div><div><span>First workflow question</span><strong>{research.discoveryQuestion}</strong></div><div><span>Likely objection</span><strong>{research.likelyObjection ?? "Not enough evidence"}</strong><small>{research.evidenceSafeResponse}</small></div><div><span>Smallest service hypothesis</span><strong>{research.smallestLikelyService.replaceAll("_", " ")}</strong><small>{research.serviceReason}</small></div></div>
        <div className="prohibited-claims"><div><ShieldAlert size={16} /><span>Claims {profile.agent.name} must not make</span></div><ul>{research.prohibitedClaims.map((claim) => <li key={claim}>{claim}</li>)}</ul></div>
        <div className="research-actions"><form action={refreshLeadResearchProfile} className="research-action"><input type="hidden" name="id" value={lead.id} /><button className="secondary-button"><RefreshCw size={14} /> Rebuild from verified CRM evidence</button><small>Last generated {formatDateTime(lead.research_profile_updated_at)}</small></form><form action={queueDeepResearch} className="research-action"><input type="hidden" name="leadId" value={lead.id} /><button className="secondary-button"><Microscope size={14} /> Queue deeper audit</button><small>Use only for unusually valuable prospects; human verification is still required.</small></form></div>
      </article>
      <article className="panel span-2"><div className="panel-heading"><div><span className="eyebrow">Conversation history</span><h2>Calls and transcripts</h2></div></div>{calls.length ? <div className="call-list">{calls.map((call) => <details key={String(call.id)} className="call-card"><summary><div className="call-summary-main"><strong>{formatDateTime(call.finalized_at as string | null)}</strong><span>{Number(call.talk_seconds)} seconds · {String(call.network_outcome || call.lifecycle)}</span><p className="call-summary-preview">{String(call.summary || "Summary will appear as soon as the call finalizes.")}</p></div><Badge status={String(call.task_success || call.network_outcome)}>{String(call.task_success || call.network_outcome || "processing")}</Badge></summary><div className="call-body"><p>{String(call.summary || "No AI summary stored yet.")}</p><ConversationScorecard analysis={call.ai_analysis} /><p className="recording-note">The transcript and summary are stored permanently even after the source recording link expires.</p><div className="transcript">{Array.isArray(call.transcript) ? call.transcript.map((line: { role?: string; text?: string }, index: number) => <div key={index} className={`transcript-line ${line.role === "assistant" ? "assistant" : "prospect"}`}><span>{line.role === "assistant" ? profile.agent.name : "Prospect"}</span><p>{line.text}</p></div>) : null}</div></div></details>)}</div> : <EmptyState title="No calls yet" body="This lead has no imported or cloud calls." />}</article>
      <article className="panel"><div className="panel-heading"><div><span className="eyebrow">Next actions</span><h2>Follow-ups</h2></div></div>{followUps.length ? followUps.map((item) => <div className="mini-row" key={String(item.id)}><div><strong>{String(item.type)}</strong><span>{String(item.status)} · {formatDateTime(item.due_at as string | null)}</span></div></div>) : <EmptyState title="No follow-up" body="AI and deterministic call rules create tasks here." />}</article>
      <article className="panel span-2"><div className="panel-heading"><div><span className="eyebrow">Human handoff</span><h2>Meeting preparation briefs</h2></div><Link href="/meetings">View all</Link></div>{meetingBriefs.length ? <div className="meeting-brief-list">{meetingBriefs.map((item) => {
        const brief = item.brief && typeof item.brief === "object" ? item.brief as Record<string, unknown> : {};
        const agenda = Array.isArray(brief.recommendedAgenda) ? brief.recommendedAgenda.map(String) : [];
        return <div className="meeting-brief-row" key={String(item.id)}><div><strong>{String(brief.objective || "Confirm the workflow before recommending scope.")}</strong><span>{String(brief.meetingStatus || item.status).replaceAll("_", " ")} · {formatDateTime((brief.confirmedAt || item.meeting_at) as string | null)}</span></div>{agenda.length ? <ol>{agenda.slice(0, 3).map((point, index) => <li key={`${point}-${index}`}>{point}</li>)}</ol> : <small>Agenda will appear when the transcript contains enough evidence.</small>}</div>;
      })}</div> : <EmptyState title="No meeting brief" body="A brief appears after a calendar-link follow-up or confirmed meeting." />}</article>
    </section>
  </>;
}
